name: moviescollection
description: Collection of Movies.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  flutter_bloc: ^7.0.1
  dartz: ^0.10.0
  equatable: ^2.0.0
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.3
  lottie: ^1.1.0
  shared_preferences: ^2.0.5
  cached_network_image: ^3.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.0.15
  bloc_test:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/movies.png
    - assets/images/movie.png
    - assets/images/arrow-right-alt.png
    - assets/movie-loading.json
